# noinspection SpellCheckingInspection
spring.application.name=obar-web
server.port=${WEB_PORT:8080}
spring.thymeleaf.cache=false
spring.config.import=optional:file:.env[.properties],optional:file:../.env[.properties]
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

obar.core.lifecycle.enabled=${OBAR_CORE_LIFECYCLE_ENABLED:true}
openrouteservice.api-key=${OPENROUTESERVICE_API_KEY:}
openrouteservice.base-url=${OPENROUTESERVICE_BASE_URL:https://api.openrouteservice.org}
nominatim.base-url=${NOMINATIM_BASE_URL:https://nominatim.openstreetmap.org}
osrm.base-url=${OSRM_BASE_URL:https://router.project-osrm.org}
supabase.url=${SUPABASE_URL:https://oqgdapuibldohxfnbkfo.supabase.co}
supabase.publishable-key=${SUPABASE_PUBLISHABLE_KEY:}
supabase.secret-key=${SUPABASE_SECRET_KEY:}
supabase.user-photo-bucket=${SUPABASE_USER_PHOTO_BUCKET:user-photos}
supabase.vehicle-photo-bucket=${SUPABASE_VEHICLE_PHOTO_BUCKET:vehicle-photos}
