# noinspection SpellCheckingInspection
spring.application.name=obar-web
server.port=${WEB_PORT:8080}
spring.thymeleaf.cache=false

obar.core.lifecycle.enabled=${OBAR_CORE_LIFECYCLE_ENABLED:true}
openrouteservice.api-key=${OPENROUTESERVICE_API_KEY:}
openrouteservice.base-url=${OPENROUTESERVICE_BASE_URL:https://api.openrouteservice.org}
nominatim.base-url=${NOMINATIM_BASE_URL:https://nominatim.openstreetmap.org}
osrm.base-url=${OSRM_BASE_URL:https://router.project-osrm.org}
